undef_action: warn
out: /cmap/cmap-query/production/compute-daemon/utils/my_analysis.sig_queryl1k_tool.6ab8cd8ffc10910013ed2767
runtests: false
rundemo: false
rpt: NAFLD381genes
create_subdir: false
verbose: true
encode_url: false
config: http://data.clue.io/api/s.esen@ug.bilkent.edu.tr/results/Sep_27_2026/my_analysis.sig_queryl1k_tool.6ab8cd8ffc10910013ed2767/config.yaml
up: http://data.clue.io/api/s.esen%40ug.bilkent.edu.tr/results/Sep_27_2026/my_analysis.sig_queryl1k_tool.6ab8cd8ffc10910013ed2767/up.gmt
down: http://data.clue.io/api/s.esen%40ug.bilkent.edu.tr/results/Sep_27_2026/my_analysis.sig_queryl1k_tool.6ab8cd8ffc10910013ed2767/down.gmt
score: /cmap/data/M2/level5_modz_n1165466x12328.gctx
rank: /cmap/data/M2/level5_rank_bing_n1165466x10174.gctx
sig_meta: /cmap/data/M2/siginfo.txt
metric: wtcs
es_tail: both
query_meta: []
ncs_group: []
save_minimal: true
save_digests: true
exemplar_field: is_exemplar_sig
max_col: 50000.0
